apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-bot
  template:
    metadata:
      labels:
        app: policy-bot
    spec:
      containers:
      - name: bot
        image: palantirtechnologies/policy-bot:1.25.0
        ports:
        - containerPort: 8080
          name: web
        resources:
          limits:
            memory: 1Gi
            cpu: 1
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: GITHUB_APP_INTEGRATION_ID
            valueFrom:
              secretKeyRef:
                name: github-secret
                key: GITHUB_APP_INTEGRATION_ID
          - name: GITHUB_APP_WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                name: github-secret
                key: GITHUB_APP_WEBHOOK_SECRET
          - name: GITHUB_OAUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: github-secret
                key: GITHUB_OAUTH_CLIENT_ID
          - name: GITHUB_OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: github-secret
                key: GITHUB_OAUTH_CLIENT_SECRET
          - name: GITHUB_APP_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: github-secret
                key: GITHUB_APP_PRIVATE_KEY



