apiVersion: v1
kind: ServiceAccount
metadata:
  name:  ensure-secret-sa
  annotations:
    argocd.argoproj.io/hook: PreSync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ensure-secret-sa
  annotations:
    argocd.argoproj.io/hook: PreSync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ensure-secret-sa
subjects:
- kind: ServiceAccount
  name: ensure-secret-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ensure-secret-hook
  annotations:
    argocd.argoproj.io/hook: PreSync
rules:
- apiGroups:
  - "*" # terrible idea in a real system
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: ensure-secret-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      serviceAccountName: ensure-secret-sa
      containers:
      - name: ensure-secret
        image: alpine/k8s
        command:
          - "sh"
          - "/opt/ensure-secrets/run.sh"
        volumeMounts:
        - name: ensure-secrets-cm
          mountPath: /opt/ensure-secrets
      restartPolicy: Never
      volumes:
        - name: ensure-secrets-cm
          configMap:
            name: ensure-secrets-cm
  backoffLimit: 2
