apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: policy-bot

configMapGenerator:
  - name: policy-bot-cm
    files:
      - policy-bot.yml=config/policy-bot.yml

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
# - ensure-secret-hook.yaml
